services:
  - type: web
    name: cambostation
    runtime: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile.allinone
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
